# STAGE 1 : build the frontend
FROM node:20-alpine AS frontend-builder

WORKDIR /app

COPY ./frontend/package*.json /app

RUN npm install

COPY ./frontend /app

RUN npm run build

# Stage 2 - FullStack image

FROM node:20-alpine

WORKDIR /app

COPY ./backend/package*.json ./

RUN npm install

COPY ./backend /app

COPY --from=frontend-builder /app/dist /app/public

CMD ["node","server.js"]

